---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: .ci/gitlab/ci.yml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
        exclude: src/pymor/algorithms/rules.py
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: ^src/pymordemos/spe10channel/perm_case1.dat$
      - id: file-contents-sorter
        files: ^\.mailmap$
      - id: mixed-line-ending
        exclude: ^src/pymordemos/spe10channel/perm_case1.dat$
      - id: no-commit-to-branch
        args:
          - -b
          - main
          - -b
          - pymor-paper
          - -p
          - \d+\.\d+\.x
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
        exclude: ^src/pymordemos/spe10channel/perm_case1.dat$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        args:
          - --fix
  - repo: https://github.com/pappasam/toml-sort.git
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.17.0
    hooks:
      - id: yamlfix
        types:
          - text
        files: \.yaml|\.yml|\.cff$
        exclude: ^conda
ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
